In [11]:
#one dimension
#decrease the number of lines of codes
import numpy as np
print(type(np.array([1,2,3,4,5])))

<class 'numpy.ndarray'>


In [12]:
print(np.array([[1,2,3],[4,5,6],[7,8,9]]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
#3 dimension
print(np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [18]:
#check how many dimensions in an array
a=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.ndim)
print(b.ndim)

3
2


In [23]:
#access array elements
print(a[0])
print(a[1])

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [27]:
#to print the specific element in an 2D array
print("The 2nd element on the first row:",b[1,2])
r=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(r[1,2])

The 2nd element on the first row: 6
8


In [30]:
#to access the elements in a 3D array
p=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
#p(first outer bracket, 2nd outr brkt, 3rd inner brkt)
print(p[1,0,2])


9


In [31]:
#data types in numpy
#i=integer
#b=boolean
#u=unsigned integer
print(a.dtype)

int32


In [32]:
#create an array with data type integer
import numpy as np
e=np.array([1,2,3,4,5], dtype='i')
print(e)
print(e.dtype)

[1 2 3 4 5]
int32


In [45]:
#create an array with data type 4bytes integer
import numpy as np
o=np.array([1,2,3,4,5], dtype='i4')
print(o)
print(o.dtype)

[1 2 3 4 5]
int32


In [36]:
#slicing array [start:end]
import numpy as np
k=np.array([1,2,3,4,5,6,7,8,9])
print(k[1:5])
print(k[1:])

[2 3 4 5]
[2 3 4 5 6 7 8 9]


In [40]:
#slicing 2D array
import numpy as np
j=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(j[1,1:4])

[7 8 9]


In [47]:
#make a copy, display the original array and display both
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
x=arr.copy()
arr[0]=42
print("original array:",arr)
print("Copy array:",x)

original array: [42  2  3  4  5  6  7  8  9]
Copy array: [1 2 3 4 5 6 7 8 9]


In [49]:
#if we use view(), the change in the original array reflect on copy
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
x=arr.view()
arr[0]=42
print("original array:",arr)
print("Copy array:",x)

original array: [42  2  3  4  5  6  7  8  9]
Copy array: [42  2  3  4  5  6  7  8  9]


In [53]:
#shape of array
import numpy as np
w=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(w.shape)

(3, 3)


In [60]:
#reshaping array
import numpy as np
q=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newa=q.reshape(4,3)
print(newa.ndim)
print(newa)

2
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [63]:
#flattering array
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [64]:
#iterating array
import numpy as np
s=np.array([1,2,3,4,5,6,7,8,9])
for i in s:
    print(i)

1
2
3
4
5
6
7
8
9


In [66]:
#accessing elements of a 2D matrix 
import numpy as np
w=np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in w:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9


In [68]:
#accessing elements of 3D array
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in a:
    for j in i:
        for t in j:
            print(t)

1
2
3
4
5
6
7
8
9
10
11
12


In [10]:
#concatenate arrays 
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
v=np.concatenate((a,b,c))
print(v)

[1 2 3 4 5 6 7 8 9]


In [18]:
#join two 2D arrays along rows (axis=1)
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
b=np.array([[1,2,3,4],[5,6,7,8]])
array=np.concatenate((a,b),axis=1)
print(array)

[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


In [7]:
s#searching array finding indexs
import numpy as np
arr=np.array([1,2,3,4,4,5,5])
x=np.where(arr==4)
print(x)

(array([3, 4], dtype=int64),)


In [8]:
#search sort
import numpy as np
arr=np.array([6,7,8,9])
x=np.searchsorted(arr, 7)
print(x)

1


In [9]:
#search sort
import numpy as np
arr=np.array([6,7,8,9])
x=np.searchsorted(arr, 7, side='right')
print(x)

2


In [19]:
#sorting array
import numpy as np
a=np.array([9,5,36,4,6])
print(np.sort(a))

[ 4  5  6  9 36]


In [20]:
import numpy as np
g=['Apple', 'dog','cat']
print(np.sort(g))

['Apple' 'cat' 'dog']


In [21]:
#sorting 2D array
import numpy as np
arr=np.array([[1,26,5],[89,0,12]])
print(np.sort(arr))

[[ 1  5 26]
 [ 0 12 89]]


In [26]:
#generate random number
from numpy import random
a= random.randint(100)
print(a)

8


In [27]:
from numpy import random
x=random.randint(100, size=(5))
print(x)

[82 73 99 23 42]


In [28]:
from numpy import random
x=random.randint(100, size=(3,5))
print(x)

[[39 98  9 40 65]
 [98 70 79 41 60]
 [43  9 25 81 46]]


In [30]:
from numpy import random
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(100))
print(x)

[7 7 7 7 7 7 5 7 7 7 5 3 5 5 5 7 5 7 7 7 5 5 5 5 7 5 5 7 7 3 7 5 3 7 7 7 7
 7 5 5 7 7 7 5 7 7 7 7 7 7 5 7 5 7 7 5 7 5 5 5 7 5 5 7 7 7 5 7 7 5 5 7 7 7
 7 5 3 7 7 7 3 7 7 7 7 7 7 7 7 5 7 7 5 7 5 7 7 5 7 7]
